log4j.rootLogger = DEBUG, GayGame

log4j.appender.GayGame = org.apache.log4j.ConsoleAppender
log4j.appender.GayGame.layout = org.apache.log4j.PatternLayout
log4j.appender.GayGame.layout.conversionPattern=%m%n